---
- name: Git clone infra-core
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/infra-core.git"
    dest: "/home/infra/repos/infra-core"
    version: "master"
    update: false
    accept_hostkey: true
  become: true
  become_user: infra

- name: Create symlink to ansible
  ansible.builtin.file:
    src: "/home/infra/repos/ansible"
    dest: "/home/infra/ansible"
    state: link
    owner: "{{ user_infra_name }}"
    group: "{{ user_infra_name }}"
  become: true
  become_user: infra

- name: Create symlink to docker
  ansible.builtin.file:
    src: "/home/infra/repos/infra-core/tools/docker"
    dest: "/home/infra/docker"
    state: link
    owner: "{{ user_infra_name }}"
    group: "{{ user_infra_name }}"
  become: true
  become_user: infra

- name: Create symlink to secrets
  ansible.builtin.file:
    src: "/home/infra/repos/infra-core/secrets"
    dest: "/home/infra/secrets"
    state: link
    owner: "{{ user_infra_name }}"
    group: "{{ user_infra_name }}"
  become: true
  become_user: infra
