---
- name: git clone ansible
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/ansible.git"
    dest: "/home/infra/repos/ansible-common"
    version: "master"
    update: false
    accept_hostkey: true
  become: true
  become_user: infra
