---
- name: restart zabbix-agent2
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: true

- name: restart zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: true

- name: restart php8.1-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted
    enabled: true

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true

- name: restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true
