---
database:
  hosts:
    database1003:
      ansible_host: 10.210.4.3

monitor:
  hosts:
    monitor1002:
      ansible_host: 10.210.2.2

minecraftv2:
  hosts:
    minecraft1001:
      ansible_host: 10.210.30.1
    minecraft1002:
      ansible_host: 10.210.30.2

minecraftpanel:
  hosts:
    minecraftpanel1001:
      ansible_host: 10.210.30.31

minecraftproxy:
  hosts:
    minecraftproxy1001:
      ansible_host: 10.210.30.101

dify:
  hosts:
    dify1001:
      ansible_host: 10.210.2.3


admin.common:
  hosts:
    admin100:
      ansible_host: 10.210.2.1

dns.unbound:
  hosts:
    dns100:
      ansible_host: 10.210.2.240
    dns101:
      ansible_host: 10.210.2.241

web.common:
  hosts:
    web100:
      ansible_host: 10.210.2.5
    web101:
      ansible_host: 10.210.2.6

# web.ptero-panel:
#   hosts:
#     web000:
#       ansible_host:

app.common:
  hosts:
    app100:
      ansible_host: 10.210.2.9

# app.ptero-node:
#   hosts:
#     app000:
#       ansible_host:
