---
database:
  hosts:
    database1003:
      ansible_host: 10.210.4.3

monitor:
  hosts:
    monitor1002:
      ansible_host: 10.210.2.2

admin:
  hosts:
    admin1001:
      ansible_host: 10.210.6.1

unbound:
  hosts:
    unbound1001:
      ansible_host: 10.210.9.1

minecraftv2:
  hosts:
    minecraft1001:
      ansible_host: 10.210.30.1
    minecraft1002:
      ansible_host: 10.210.30.2


minecraftpanel:
  hosts:
    minecraftpanel1001:
      ansible_host: 10.210.30.31

minecraftproxy:
  hosts:
    minecraftproxy1001:
      ansible_host: 10.210.30.101

gateway:
  hosts:
    gateway1001:
      ansible_host: 10.210.3.1

dify:
  hosts:
    dify1001:
      ansible_host: 10.210.2.3

wiki:
  hosts:
    wiki1001:
      ansible_host: 10.210.11.11
