---
all:
  children:
    kanagawa01:
      children:
        kng01_mgmt:
          hosts:
            kng01-recursive-dns-01:
              ansible_host: 10.10.10.240
            kng01-recursive-dns-02:
              ansible_host: 10.10.10.241
            kng01-zabbix-01:
              ansible_host: 10.10.10.250
            kng01-mgmt-connector-01:
              ansible_host: 10.10.10.20

        kng01_dmz:
          hosts:
            kng01-pterodactyl-panel-01:
              ansible_host: 10.10.30.31
            kng01-minecraft-node-01:
              ansible_host: 10.10.30.10

        kng01_client:
          hosts: {}

  vars:
    ansible_user: ops
    ansible_become: true
