---
- name: Setup admin.common
  hosts: admin.common
  ignore_unreachable: true

  roles:
    - ../../roles/common/lxc
    - ../../roles/common/cloudflare-ssh
    - ../../roles/middleware/python3-pip
    - ../../roles/middleware/ansible
    - ../../roles/middleware/terraform
