---
- name: Clone terraform-cloudflare-tunnel
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/terraform-cloudflare-tunnel.git"
    dest: "~/repos/terraform-cloudflare-tunnel"
    version: "master"
    update: false
    accept_hostkey: true
