---
- name: Git clone terraform-proxmox
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/ansible-proxmox.git"
    dest: "/home/infra/repos/terraform-proxmox"
    version: "master"
    update: false
    accept_hostkey: true
  become: true
  become_user: infra
