---
- name: Clone terraform-dns
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/terraform-dns.git"
    dest: "~/repos/terraform-dns"
    version: "master"
    update: false
    accept_hostkey: true
