---
- name: Git clone terraform-oraclecloud
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/terraform-oraclecloud.git"
    dest: "/home/infra/repos/terraform-oraclecloud"
    version: "master"
    update: false
    accept_hostkey: true
  become: true
  become_user: infra
