---
- name: Setup web.ptero-panel
  hosts: web.ptero-panel
  ignore_unreachable: true

  roles:
    - ../../roles/common/lxc
    - ../../roles/middleware/mysql-server
    - ../../roles/middleware/redis-server
    - ../../roles/middleware/php
    - ../../roles/middleware/nginx  # FIXME: Replace with Caddy
