---
- name: Copy 99-zabbix.ini
  template:
    src: ./etc/php/8.1/fpm/conf.d/99-zabbix.ini
    dest: /etc/php/8.1/fpm/conf.d/99-zabbix.ini
    owner: root
    group: root
    mode: 0644
  notify: restart php8.1-fpm

- name: Enable php-fpm
  ansible.builtin.systemd_service:
    name: php8.1-fpm
    enabled: true
    state: started
