---
- name: unattended-upgrades
  ansible.builtin.include_tasks:
    file: unattended-upgrades.yml
  when:
    - not skip_unattended_upgrades | default(false)

- name: zabbix-agent
  ansible.builtin.include_tasks:
    file: zabbix-agent.yml
  when:
    - not skip_zabbix_agent | default(false)

- name: secrets
  ansible.builtin.include_tasks:
    file: secrets.yml
  when:
    - not skip_secrets | default(false)

- name: etckeeper
  ansible.builtin.include_tasks:
    file: etckeeper.yml
  when:
    - not skip_etckeeper | default(false)
