---
- name: package
  ansible.builtin.include_tasks:
    file: package.yml

- name: unattended-upgrades
  ansible.builtin.include_tasks:
    file: unattended-upgrades.yml
  when:
    - not skip_unattended_upgrades | default(false)

- name: zabbix-agent
  ansible.builtin.include_tasks:
    file: zabbix-agent.yml
  when:
    - not skip_zabbix_agent | default(false)
