---
- name: Install Zabbix 6.0 Package
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb"
  when: ansible_facts['lsb']['release'] == "20.04"

- name: Install Zabbix 7.0 Package
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu24.04_all.deb"
  when: ansible_facts['lsb']['release'] == "22.04"
