---
- name: Setup zabbix.general
  hosts: zabbix.general
  ignore_unreachable: true

  roles:
    - ../../roles/common/lxc
    - ../../roles/middleware/mysql-server
    - ../../roles/middleware/nginx
    - ../../roles/middleware/php
    - ../../roles/middleware/zabbix-server
