---
- name: Clone ansible.git
  ansible.builtin.git:
    repo: "git@github.com:alflag-team/ansible.git"
    dest: "~/repos/ansible"
    version: "master"
    update: false
    accept_hostkey: true

- name: Create symlink to ansible
  ansible.builtin.file:
    src: "~/repos/ansible"
    dest: "~/ansible"
    state: link
