---
- name: Clone ansible
  ansible.builtin.include_tasks:
    file: git.yml
  when:
    - not skip_clone_ansible | default(false)

- name: Install ansible
  ansible.builtin.include_tasks:
    file: install.yml
  when:
    - not skip_isntall_ansible | default(false)
