---
- name: Git clone terraform-cloudflare-access
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/terraform-cloudflare-access.git"
    dest: "/home/infra/repos/terraform-cloudflare-access"
    version: "master"
    update: false
    accept_hostkey: true
  become: true
  become_user: infra
