---
- name: Git clone terraform-cloudflare-tunnel
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/terraform-cloudflare-tunnel.git"
    dest: "/home/infra/repos/terraform-cloudflare-tunnel"
    version: "master"
    update: false
    accept_hostkey: true
  become: true
  become_user: infra
