---
- name: Install php
  ansible.builtin.apt:
    name:
      - php8.1
      - php8.1-bz2
      - php8.1-cgi
      - php8.1-cli
      - php8.1-common
      - php8.1-curl
      - php8.1-gd
      - php8.1-intl
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-openssl
      - php8.1-sqlite3
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-yaml
      - php8.1-zip
      - php8.1-zlib
    state: present
