---
- name: Install php
  ansible.builtin.apt:
    name:
      - php
      - php-bcmath
      - php-cli
      - php-common
      - php-curl
      - php-dev
      - php-fpm
      - php-gd
      - php-igbinary
      - php-imagick
      - php-intl
      - php-ldap
      - php-mbstring
      - php-memcached
      - php-msgpack
      - php-mysql
      - php-opcache
      - php-readline
      - php-redis
      - php-soap
      - php-xdebug
      - php-xml
      - php-xmlrpc
      - php-zip
    state: present

- name: Start php-fpm
  ansible.builtin.systemd_service:
    name: php-fpm
    state: started
    enabled: true
