---
- name: Install php
  ansible.builtin.apt:
    name:
      - php8.3
      - php8.3-bcmath
      - php8.3-cli
      - php8.3-common
      - php8.3-curl
      - php8.3-dev
      - php8.3-fpm
      - php8.3-gd
      - php8.3-igbinary
      - php8.3-imagick
      - php8.3-intl
      - php8.3-ldap
      - php8.3-mbstring
      - php8.3-memcached
      - php8.3-msgpack
      - php8.3-mysql
      - php8.3-opcache
      - php8.3-readline
      - php8.3-redis
      - php8.3-soap
      - php8.3-xdebug
      - php8.3-xml
      - php8.3-xmlrpc
      - php8.3-zip
    state: present

- name: Start php-fpm
  ansible.builtin.systemd_service:
    name: php8.3-fpm
    state: started
    enabled: true
