---
- name: Copy sshd_config
  ansible.builtin.copy:
    src: ./etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart sshd

- name: Copy sshd_config.d/99-password-auth.conf
  ansible.builtin.copy:
    src: ./etc/ssh/sshd_config.d/99-password-auth.conf
    dest: /etc/ssh/sshd_config.d/99-password-auth.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart sshd

- name: Delete sshd_config.d/60-cloudimg-settings.conf
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
    state: absent
  become: true
  notify:
    - restart sshd
